In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text':['Learbay teaches NLP','Leanbay writes comments','people read comments','NLP is good']})
df.head()

text
0      Learbay teaches NLP
1  Leanbay writes comments
2     people read comments
3              NLP is good

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df['text'])

In [4]:
# converted into numbers - 
print(cv.vocabulary_)

{'learbay': 4, 'teaches': 8, 'nlp': 5, 'leanbay': 3, 'writes': 9, 'comments': 0, 'people': 6, 'read': 7, 'is': 2, 'good': 1}


In [5]:
# sentence 1 - 
bow[0].toarray()

array([[0, 0, 0, 0, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [6]:
# sentence 2-
bow[1].toarray()

array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [9]:
# ignore new words - 
cv.transform(['Leanbay also teaches DS along with NLP']).toarray()

array([[0, 0, 0, 1, 0, 1, 0, 0, 1, 0]], dtype=int64)

In [11]:
# hyperparameter - top 2 words
cv1 = CountVectorizer(max_features=2,binary=True)
bow = cv1.fit_transform(df['text'])

In [12]:
print(cv1.vocabulary_)

{'nlp': 1, 'comments': 0}


In [13]:
import nltk

In [18]:
eg = "Iceland is a small island 1173 nation that is Europe's westernmost country and home to the world’s northernmost capital, Reykjavik. Eleven percent of the country is covered in glacial ice and is surrounded by water. If global warming continues, rising water levels and melting ice could be devastating to Iceland."
eg

"Iceland is a small island 1173 nation that is Europe's westernmost country and home to the world’s northernmost capital, Reykjavik. Eleven percent of the country is covered in glacial ice and is surrounded by water. If global warming continues, rising water levels and melting ice could be devastating to Iceland."

In [19]:
import re
from nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer

In [20]:
lemm = WordNetLemmatizer()
sen = nltk.sent_tokenize(eg)
corpus = []
for i in range(len(sen)):
    words = re.sub('[^a-zA-Z0-9]',' ',sen[i])
    words = words.lower()
    words = words.split()
    words = [lemm.lemmatize(x) for x in words if not x in set(stopwords.words('english'))]
    words = ' '.join(words)
    corpus.append(words)

In [21]:
corpus

['iceland small island 1173 nation europe westernmost country home world northernmost capital reykjavik',
 'eleven percent country covered glacial ice surrounded water',
 'global warming continues rising water level melting ice could devastating iceland']

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 10,binary = True)
bow = cv.fit_transform(corpus).toarray()
bow

array([[1, 0, 1, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 1, 0, 0, 1, 1]], dtype=int64)